In [7]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("Resources/dementia_patients_health_data.csv")
df.head()


FileNotFoundError: [Errno 2] No such file or directory: 'Resources/dementia_patients_health_data.csv'

In [ ]:

df = df[["Diabetic", "AlcoholLevel", "HeartRate", "BloodOxygenLevel", "BodyTemperature", "Weight", "MRI_Delay", "Age", "Education_Level",  "Dominant_Hand", "Gender", "Family_History", "Smoking_Status",  "Physical_Activity", "Depression_Status", "Medication_History", "Nutrition_Diet", "Sleep_Quality"]]
df.head()


Diabetic  AlcoholLevel  HeartRate  BloodOxygenLevel  BodyTemperature  \
0         1      0.084974         98         96.230743        36.224852   
1         0      0.016973         78         93.032122        36.183874   
2         0      0.009000         89         93.566504        37.326321   
3         0      0.086437         60         93.906510        37.030620   
4         1      0.150747         67         97.508994        36.062121   

      Weight  MRI_Delay  Age   Education_Level Dominant_Hand  Gender  \
0  57.563978  36.421028   60    Primary School          Left  Female   
1  56.832335  31.157633   61  Secondary School         Right    Male   
2  59.759066  37.640435   69    Primary School         Right    Male   
3  58.266471  50.673992   78  Secondary School          Left  Female   
4  67.705027  27.810601   77  Secondary School         Right    Male   

  Family_History  Smoking_Status  Physical_Activity Depression_Status  \
0             No  Current Smoker          Sedentary                No   
1             No   Former Smoker  Moderate Activity                No   
2            Yes   Former Smoker  Moderate Activity                No   
3            Yes    Never Smoked      Mild Activity               Yes   
4            Yes    Never Smoked      Mild Activity                No   

  Medication_History      Nutrition_Diet Sleep_Quality  
0                 No       Low-Carb Diet          Poor  
1                Yes       Low-Carb Diet          Poor  
2                 No  Mediterranean Diet          Poor  
3                Yes       Balanced Diet          Poor  
4                Yes       Low-Carb Diet          Good

In [ ]:

df.info()
df = df.dropna()
df.isnull().sum()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Diabetic            1000 non-null   int64  
 1   AlcoholLevel        1000 non-null   float64
 2   HeartRate           1000 non-null   int64  
 3   BloodOxygenLevel    1000 non-null   float64
 4   BodyTemperature     1000 non-null   float64
 5   Weight              1000 non-null   float64
 6   MRI_Delay           1000 non-null   float64
 7   Age                 1000 non-null   int64  
 8   Education_Level     1000 non-null   object 
 9   Dominant_Hand       1000 non-null   object 
 10  Gender              1000 non-null   object 
 11  Family_History      1000 non-null   object 
 12  Smoking_Status      1000 non-null   object 
 13  Physical_Activity   1000 non-null   object 
 14  Depression_Status   1000 non-null   object 
 15  Medication_History  1000 non-null   object 
 16  Nutriti

Diabetic              0
AlcoholLevel          0
HeartRate             0
BloodOxygenLevel      0
BodyTemperature       0
Weight                0
MRI_Delay             0
Age                   0
Education_Level       0
Dominant_Hand         0
Gender                0
Family_History        0
Smoking_Status        0
Physical_Activity     0
Depression_Status     0
Medication_History    0
Nutrition_Diet        0
Sleep_Quality         0
dtype: int64

In [ ]:

def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map


In [ ]:
"Diabetic", 
"AlcoholLevel",
"BodyTemperature",
"MRI_Delay",
"Education_Level",
"Dominant_Hand",
"Family_History", 
"Medication_History",


('Medication_History',)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_diabetes = LabelEncoder()
df['Diabetic'] = le_diabetes.fit_transform(df['Diabetic'])
df["Diabetic"].unique()


array([1, 0])

In [ ]:

le_alcohollvl = LabelEncoder()
df['AlcoholLevel'] = le_alcohollvl.fit_transform(df['AlcoholLevel'])
df["AlcoholLevel"].unique()


array([432,  93,  46, 441, 742, 580,  88, 798,  85, 494, 351, 417, 155,
       447, 772, 833, 202, 167, 787, 986, 473, 455, 260,  10, 766, 540,
       560, 284, 705, 722,  89, 329, 956, 835, 652, 739, 409, 826, 509,
       232, 564, 293, 725, 961, 227, 376, 697, 130, 264, 448, 148, 937,
       271, 496, 522, 551, 843, 649, 764, 713, 262,   4, 890, 219, 163,
       275, 406, 512, 610, 641, 719, 603, 538, 732, 703, 414,  90, 152,
       195, 588,   8,  29, 910, 120, 819, 407, 563, 886, 894, 884, 423,
        50, 419, 663,  76, 545, 124, 114, 162, 245, 622, 462, 157, 504,
       790, 386, 816, 619, 428, 783, 741, 236, 860, 370, 499, 943, 463,
        26, 925, 178, 847, 390, 654, 919, 665, 266, 707, 145, 994, 544,
        31, 920,  69, 679,  30, 813,   9, 933, 159, 111, 985, 880,  38,
        61,  81, 912, 230, 420, 200, 479,  19, 696,  23, 218, 464, 976,
       566, 324, 395, 196,   1, 907, 909, 123, 768, 714, 342, 990, 187,
       808, 452, 388, 743, 297, 140,  56, 831, 518, 302, 394, 51

In [ ]:

le_bodytemp = LabelEncoder()
df['BodyTemperature'] = le_bodytemp.fit_transform(df['BodyTemperature'])
df["BodyTemperature"].unique()


array([149, 124, 883, 670,  39, 444, 666,  30, 622, 251, 739, 333, 410,
       918, 542,   4, 711, 376, 979, 264, 756, 812, 349,  51, 479, 517,
       694, 154, 368, 889, 943,  37, 700, 611, 101, 440, 576, 989, 899,
       419, 626, 254, 546, 371, 466, 676, 974,  52, 183, 981, 204, 511,
       433,  76, 774, 567, 180,  47, 667,  14, 660, 992, 129, 196, 385,
       442, 890, 944, 120, 592, 467, 490, 514, 731, 325,  75,  81, 623,
       140, 905, 208, 752, 108, 106, 754, 822,  28, 702, 109, 107, 192,
       166, 287, 906,  33, 806, 358, 631,  64,  77, 452, 810, 991, 344,
       185, 572, 430, 431, 994,  57, 563, 232, 158, 523, 636, 422,  95,
       613, 801, 761, 391, 935, 122, 377,  74, 237, 732, 693, 472, 506,
       915, 324, 530, 429,  49, 961,  71,   8, 807, 907, 562, 825, 364,
        91, 484, 988, 187, 380, 654, 361, 581, 966, 238, 207, 339, 443,
       904, 128,  38, 939, 113, 331, 532,  44, 740, 653, 764, 369, 168,
       730, 830, 920, 783, 860, 512, 161, 155,  58, 174, 574, 23

In [ ]:

le_MRI = LabelEncoder()
df['MRI_Delay'] = le_MRI.fit_transform(df['MRI_Delay'])
df["MRI_Delay"].unique()


array([622, 522, 638, 859, 453, 341, 170, 510, 626, 834, 362, 585, 881,
       930, 134, 545, 149, 217, 640, 872, 355,  95, 285, 116, 405, 564,
       175, 248, 494, 957, 518, 379, 430, 475, 777, 700, 106, 828, 142,
       999, 507, 950, 346,   3, 382, 816, 352, 231, 645, 738, 996, 228,
       524, 868, 661, 207, 770,  50, 485, 110, 546, 850, 847, 839, 202,
        74, 803, 253, 764, 799, 848, 923, 858,  75, 643,  60, 776, 659,
       288, 986, 993, 205, 824, 397, 944, 361, 419, 429, 880, 840, 554,
       560,  71, 726, 806, 444, 129, 746, 695, 152, 939, 437, 683, 269,
       669,  92, 894, 111, 312, 390, 339, 832,   4, 580, 227, 458,  57,
        78, 697, 201, 320, 914, 909, 413, 329, 618, 745, 189, 913, 625,
       467, 936,  96, 250, 706, 791, 519, 213, 434, 509, 299, 257, 613,
       938, 268,  94,  44, 280, 244, 916, 788, 177, 474, 135, 731, 783,
       423, 236, 141, 639, 215, 468, 214,   7, 265, 624, 908, 707,  38,
       860, 882, 370, 973, 951, 517, 498, 282, 220, 888, 664, 40

In [ ]:

le_education = LabelEncoder()
df['Education_Level'] = le_education.fit_transform(df['Education_Level'])
df["Education_Level"].unique()


array([2, 3, 1, 0])

In [ ]:

le_handdom = LabelEncoder()
df['Dominant_Hand'] = le_handdom.fit_transform(df['Dominant_Hand'])
df["Dominant_Hand"].unique()


array([0, 1])

In [ ]:

le_famhist = LabelEncoder()
df['Family_History'] = le_famhist.fit_transform(df['Family_History'])
df["Family_History"].unique()


array([0, 1])

In [ ]:

le_medication = LabelEncoder()
df['Medication_History'] = le_medication.fit_transform(df['Medication_History'])
df["Medication_History"].unique()


array([0, 1])

In [ ]:

le_smoking = LabelEncoder()
df['Smoking_Status'] = le_smoking.fit_transform(df['Smoking_Status'])
df["Smoking_Status"].unique()
#le.classes_


array([0, 1, 2])

In [ ]:

le_heartrate = LabelEncoder()
df['HeartRate'] = le_heartrate.fit_transform(df['HeartRate'])
df["HeartRate"].unique()


array([38, 18, 29,  0,  7, 34, 30,  9,  4, 37, 33, 31, 35, 24, 14, 22, 16,
       39, 17,  6, 27, 15, 28, 23, 11, 10, 36,  1, 20, 25,  3, 12,  5, 13,
       19,  8,  2, 21, 32, 40, 26])

In [ ]:

le_bloodoxygen = LabelEncoder()
df['BloodOxygenLevel'] = le_bloodoxygen.fit_transform(df['BloodOxygenLevel'])
df["BloodOxygenLevel"].unique()


array([591, 261, 328, 364, 718, 424, 606, 189, 979,  38, 187, 641, 876,
       699, 343, 682, 971, 623, 303, 498, 358, 122, 922, 280, 963, 258,
       346, 907,  50, 748, 123, 573,  30, 217, 890,  33, 597, 609, 670,
       580, 866, 554,   3,  23, 119, 168, 136, 317, 818, 219, 880, 507,
       376, 885,  47, 798, 587, 603,  54, 295, 540, 594, 884, 537, 422,
       531, 161, 468, 518, 746, 741, 949, 221, 170, 284, 350, 238, 538,
       781,  85, 405, 800, 159, 323, 671,   8, 478, 788, 902, 844, 402,
       874, 371, 898, 959,  94, 871, 484, 361, 903, 349, 320, 577,  46,
       178, 289, 319,  39, 786, 900, 765, 299, 108, 535, 264, 799, 947,
        79,  36, 845, 333, 601, 910,  73, 708, 783, 712, 347, 975, 100,
       496, 590, 304, 802, 766, 690, 556, 561, 266, 747, 886, 981, 568,
       511, 400, 883, 621, 363, 574, 160, 846, 545, 943, 605, 214, 896,
       704, 643, 856, 125, 509, 711,  63, 362, 752, 382, 378,  69, 499,
       523, 373, 957, 909,  43, 325, 413, 563, 263, 420, 510, 89

In [ ]:

le_weight = LabelEncoder()
df['Weight'] = le_weight.fit_transform(df['Weight'])
df["Weight"].unique()


array([167, 156, 218, 180, 364, 346, 681, 405,  84, 182, 637, 560, 151,
       198,  95, 471, 102, 868, 341, 704, 130, 696, 518, 458, 308, 610,
       398,  16, 300,  87, 907, 690, 352, 295, 541, 996, 588, 718, 274,
       148, 347, 568,  98, 501, 382, 605, 377, 717, 798, 271, 558, 584,
       124,  59, 975,  13, 142, 530, 670,  28,  10, 843, 379, 550,  60,
       440, 165, 969, 212, 187, 189, 469, 994, 641, 288, 338, 779, 845,
       492, 113, 626, 931, 631, 340, 745, 462, 985, 663, 945, 678, 974,
       438, 229, 171, 748, 515, 309,  25, 758, 970,  30, 239, 715, 875,
       279, 294, 714,  75,  37, 697, 832,  41, 473, 983, 133, 441, 394,
       824, 495, 890, 821, 577, 859, 545, 944, 831, 276, 581, 158,  91,
       968, 210, 760, 298, 830, 918, 362, 254, 409, 207, 949, 536, 930,
       483, 114, 902, 816, 200,  63, 684, 775, 813, 655, 426, 122, 491,
       928, 679, 842, 514, 976, 987, 205, 960,  21, 889, 498, 235, 499,
       245, 709, 186, 846,  55, 919, 146, 891, 439, 674, 195,  8

In [ ]:

le_age = LabelEncoder()
df['Age'] = le_age.fit_transform(df['Age'])
df["Age"].unique()


array([ 0,  1,  9, 18, 17,  7, 27,  6, 13, 16,  4, 30, 29, 12, 25, 10, 15,
       11, 28,  3, 23, 14, 19,  5,  2, 22, 24,  8, 21, 20, 26])

In [ ]:

le_gender = LabelEncoder()
df['Gender'] = le_gender.fit_transform(df['Gender'])
df["Gender"].unique()


array([0, 1])

In [ ]:

le_physicalact = LabelEncoder()
df['Physical_Activity'] = le_gender.fit_transform(df['Physical_Activity'])
df["Physical_Activity"].unique()


array([2, 1, 0])

In [ ]:

le_depression = LabelEncoder()
df['Depression_Status'] = le_depression.fit_transform(df['Depression_Status'])
df["Depression_Status"].unique()


array([0, 1])

In [ ]:

le_nutrition = LabelEncoder()
df['Nutrition_Diet'] = le_nutrition.fit_transform(df['Nutrition_Diet'])
df["Nutrition_Diet"].unique()


array([1, 2, 0])

In [ ]:

le_sleep = LabelEncoder()
df['Sleep_Quality'] = le_sleep.fit_transform(df['Sleep_Quality'])
df["Sleep_Quality"].unique()


array([1, 0])

In [ ]:

X = df.drop("Diabetic", axis=1)
y = df["Diabetic"]


In [ ]:

from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)


LinearRegression()

In [ ]:

y_pred = linear_reg.predict(X)


In [ ]:

from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))


In [ ]:

error


0.4953914698533163

In [ ]:

from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, y.values)


DecisionTreeRegressor(random_state=0)

In [ ]:

y_pred = dec_tree_reg.predict(X)


In [ ]:

error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))


0.00


In [ ]:

from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)


RandomForestRegressor(random_state=0)

In [ ]:
y_pred = random_forest_reg.predict(X)


In [ ]:
error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))

0.19


In [ ]:


from sklearn.model_selection import GridSearchCV

max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = DecisionTreeRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)



GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [ ]:




regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))



0.49


In [ ]:


X



AlcoholLevel  HeartRate  BloodOxygenLevel  BodyTemperature  Weight  \
0             432         38               591              149     167   
1              93         18               261              124     156   
2              46         29               328              883     218   
3             441          0               364              670     180   
4             742          7               718               39     364   
..            ...        ...               ...              ...     ...   
995           413         27               357              318       8   
996           718         37               421              178     899   
997           377          5               833              701     607   
998           213         11               131              679     927   
999           437         30               513               10     170   

     MRI_Delay  Age  Education_Level  Dominant_Hand  Gender  Family_History  \
0          622    0                2              0       0               0   
1          522    1                3              1       1               0   
2          638    9                2              1       1               1   
3          859   18                3              0       0               1   
4          453   17                3              1       1               1   
..         ...  ...              ...            ...     ...             ...   
995        711   28                0              0       1               1   
996        886   20                2              0       0               0   
997        211    7                2              1       0               0   
998        270    2                1              0       1               1   
999        504   20                3              0       0               1   

     Smoking_Status  Physical_Activity  Depression_Status  Medication_History  \
0                 0                  2                  0                   0   
1                 1                  1                  0                   1   
2                 1                  1                  0                   0   
3                 2                  0                  1                   1   
4                 2                  0                  0                   1   
..              ...                ...                ...                 ...   
995               2                  0                  0                   0   
996               2                  1                  0                   1   
997               2                  2                  0                   1   
998               2                  2                  1                   0   
999               2                  0                  0                   1   

     Nutrition_Diet  Sleep_Quality  
0                 1              1  
1                 1              1  
2                 2              1  
3                 0              1  
4                 1              0  
..              ...            ...  
995               0              1  
996               1              1  
997               0              0  
998               1              0  
999               2              0  

[1000 rows x 17 columns]

In [ ]:



X_1 = np.array([[0.08, 98, 96.23, 36.22, 57.56, 36.42, 60, 'Prirmary School', 'Left', 'Female', 'No', 'Current Smoker', 'Negative', 'Sedentary', 'No', 'No', 'Low-Carb Diet', 'Poor', 'Diabetes']])
X_1


array([['0.08', '98', '96.23', '36.22', '57.56', '36.42', '60',
        'Prirmary School', 'Left', 'Female', 'No', 'Current Smoker',
        'Negative', 'Sedentary', 'No', 'No', 'Low-Carb Diet', 'Poor',
        'Diabetes']], dtype='<U32')

In [ ]:
# Concatenate training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_combined = pd.concat([X_train, X_test])

# Fit the LabelEncoders on the combined dataset
le_alcohollvl.fit(X_combined.iloc[:, 0])
le_heartrate.fit(X_combined.iloc[:, 1])
le_bloodoxygen.fit(X_combined.iloc[:, 2])
le_bodytemp.fit(X_combined.iloc[:, 3])
le_weight.fit(X_combined.iloc[:, 4])
le_MRI.fit(X_combined.iloc[:, 5])
le_age.fit(X_combined.iloc[:, 6])
le_education.fit(X_combined.iloc[:, 7])
le_handdom.fit(X_combined.iloc[:, 8])
le_gender.fit(X_combined.iloc[:, 9])
le_famhist.fit(X_combined.iloc[:, 10])
le_smoking.fit(X_combined.iloc[:, 11])
le_physicalact.fit(X_combined.iloc[:, 12])
le_depression.fit(X_combined.iloc[:, 13])
le_medication.fit(X_combined.iloc[:, 14])
le_nutrition.fit(X_combined.iloc[:, 15])
le_sleep.fit(X_combined.iloc[:, 16])

# Transform the features using LabelEncoders
X.iloc[:, 0] = le_alcohollvl.transform(X.iloc[:, 0])
X.iloc[:, 1] = le_heartrate.transform(X.iloc[:, 1])
X.iloc[:, 2] = le_bloodoxygen.transform(X.iloc[:, 2])
X.iloc[:, 3] = le_bodytemp.transform(X.iloc[:, 3])
X.iloc[:, 4] = le_weight.transform(X.iloc[:, 4])
X.iloc[:, 5] = le_MRI.transform(X.iloc[:, 5])
X.iloc[:, 6] = le_age.transform(X.iloc[:, 6])
X.iloc[:, 7] = le_education.transform(X.iloc[:, 7])
X.iloc[:, 8] = le_handdom.transform(X.iloc[:, 8])
X.iloc[:, 9] = le_gender.transform(X.iloc[:, 9])
X.iloc[:, 10] = le_famhist.transform(X.iloc[:, 10])
X.iloc[:, 11] = le_smoking.transform(X.iloc[:, 11])
X.iloc[:, 12] = le_physicalact.transform(X.iloc[:, 12])
X.iloc[:, 13] = le_depression.transform(X.iloc[:, 13])
X.iloc[:, 14] = le_medication.transform(X.iloc[:, 14])
X.iloc[:, 15] = le_nutrition.transform(X.iloc[:, 15])
X.iloc[:, 16] = le_sleep.transform(X.iloc[:, 16])


# Convert X to float
X = X.astype(float)


In [ ]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


Shape of X: (1000, 17)
Shape of y: (1000,)


In [ ]:




y_pred = regressor.predict(X)
y_pred



array([0.53658537, 0.46238938, 0.46238938, 0.53658537, 0.79591837,
       0.53658537, 0.46238938, 0.79591837, 0.46238938, 0.53658537,
       0.53658537, 0.46238938, 0.46238938, 0.46238938, 0.53658537,
       0.14285714, 0.53658537, 0.46238938, 0.53658537, 0.46238938,
       0.53658537, 0.53658537, 0.53658537, 0.79591837, 0.53658537,
       0.46238938, 0.53658537, 0.53658537, 0.46238938, 0.46238938,
       0.53658537, 0.79591837, 0.46238938, 0.46238938, 0.46238938,
       0.53658537, 0.53658537, 0.53658537, 0.46238938, 0.46238938,
       0.46238938, 0.53658537, 0.46238938, 0.53658537, 0.46238938,
       0.53658537, 0.53658537, 0.79591837, 0.53658537, 0.53658537,
       0.53658537, 0.46238938, 0.46238938, 0.46238938, 0.53658537,
       0.53658537, 0.46238938, 0.79591837, 0.46238938, 0.79591837,
       0.53658537, 0.46238938, 0.53658537, 0.46238938, 0.46238938,
       0.53658537, 0.53658537, 0.53658537, 0.46238938, 0.53658537,
       0.53658537, 0.53658537, 0.46238938, 0.46238938, 0.53658

In [ ]:



import pickle



In [ ]:
data = {"model": regressor, "le_heartrate": le_heartrate, "le_bloodoxygen": le_bloodoxygen, "le_weight": le_weight, "le_age": le_age, "le_smoking": le_smoking, "le_gender": le_gender, "le_physicalact": le_physicalact, "le_depression": le_depression, "le_nutrition": le_nutrition, "le_sleep": le_sleep}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_heartrate = data["le_heartrate"]
le_bloodoxygen = data["le_bloodoxygen"]
le_weight = data["le_weight"]
le_age = data["le_age"] 
le_smoking = data["le_smoking"]
le_gender = data["le_gender"]
le_physicalact = data["le_physicalact"]
le_depression = data["le_depression"] 
le_nutrition = data["le_nutrition"] 
le_sleep = data["le_sleep"] 


In [ ]:

y_pred = regressor_loaded.predict(X)
y_pred
 


array([0.53658537, 0.46238938, 0.46238938, 0.53658537, 0.79591837,
       0.53658537, 0.46238938, 0.79591837, 0.46238938, 0.53658537,
       0.53658537, 0.46238938, 0.46238938, 0.46238938, 0.53658537,
       0.14285714, 0.53658537, 0.46238938, 0.53658537, 0.46238938,
       0.53658537, 0.53658537, 0.53658537, 0.79591837, 0.53658537,
       0.46238938, 0.53658537, 0.53658537, 0.46238938, 0.46238938,
       0.53658537, 0.79591837, 0.46238938, 0.46238938, 0.46238938,
       0.53658537, 0.53658537, 0.53658537, 0.46238938, 0.46238938,
       0.46238938, 0.53658537, 0.46238938, 0.53658537, 0.46238938,
       0.53658537, 0.53658537, 0.79591837, 0.53658537, 0.53658537,
       0.53658537, 0.46238938, 0.46238938, 0.46238938, 0.53658537,
       0.53658537, 0.46238938, 0.79591837, 0.46238938, 0.79591837,
       0.53658537, 0.46238938, 0.53658537, 0.46238938, 0.46238938,
       0.53658537, 0.53658537, 0.53658537, 0.46238938, 0.53658537,
       0.53658537, 0.53658537, 0.46238938, 0.46238938, 0.53658